### ISSUE TITLE
Crash in mapping Java/Maven project against SW360

### ISSUE THREAD

**Issue by Garbald** [sw360/capycli#45]
I have started a clearing run for a Java/Maven project. Maven generated the initial SBOM, this was converted and filtered with capycli. I can provide intermediate BOMs on request. I run the latest capycli version from GitHub. For the result, capycli was called as:

> python3 -m capycli bom map --nocache -i ./clearing_results/bom.json -o ./clearing_results/updated_bom.json -ov ./clearing_results/overview.json -mr ./clearing_results/mappingresult.json

CaPyCli, 2.0.1 - Map a given SBOM to data on SW360

Loading SBOM file ./clearing_results/bom.json
  Analyzing token...
  Token will expire on 2024-01-21 13:47:13
  Checking access to SW360...
No cached releases available!

Do mapping...
Retrieving package-url ids, filter: {'mav'}
Traceback (most recent call last):
  File "C:\Users\me\.pyenv\pyenv-win\versions\3.10.10\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\me\.pyenv\pyenv-win\versions\3.10.10\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\capycli\__main__.py", line 13, in <module>
    cli.main()
  File "C:\Users\me\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\capycli\main\cli.py", line 27, in main
    app.run(argv)
  File "C:\Users\me\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\capycli\main\application.py", line 157, in run
    self._run(argv)
  File "C:\Users\me\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\capycli\main\application.py", line 138, in _run
    handle_bom.run_bom_command(self.options)
  File "C:\Users\me\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\capycli\bom\handle_bom.py", line 82, in run_bom_command
    app.run(args)
  File "C:\Users\me\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\capycli\bom\map_bom.py", line 980, in run
    result = self.map_bom_to_releases(
  File "C:\Users\me\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\capycli\bom\map_bom.py", line 524, in map_bom_to_releases
    self.external_id_svc.build_purl_cache(purl_types, self.verbosity <= 1)
  File "C:\Users\me\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\capycli\common\purl_service.py", line 49, in build_purl_cache
    all_ids = all_ids + self.client.get_releases_by_external_id("package-url")
TypeError: can only concatenate list (not "dict") to list

This looks... unexpected.

**Comment by tngraf** [comment]
It is a little tricky to find out what happend exactly, because it depends on the information in your SW360 instance.  
We have released a new version of the underlying package `sw360`.  
May I ask you to rebuilt you capycli using sw360, version 13.1, then try again and report what happened?

**Comment by Garbald** [comment]
Sure. I updated sw360 to 1.3.1 (and poetry added a number of additional updates) and tried again. Regrettably the result is still the same:

> python3 -m capycli bom map --nocache -i ./clearing_results/bom.json -o ./clearing_results/updated_bom.json -ov ./clearing_results/overview.json -mr ./clearing_results/mappingresult.json

CaPyCli, 2.0.1 - Map a given SBOM to data on SW360

Loading SBOM file ./clearing_results/bom.json
  Analyzing token...
  Token will expire on 2024-01-21 13:47:13
  Checking access to SW360...
No cached releases available!

Do mapping...
Retrieving package-url ids, filter: {'mav'}
Traceback (most recent call last):
  File "C:\Users\mch04019\.pyenv\pyenv-win\versions\3.10.10\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mch04019\.pyenv\pyenv-win\versions\3.10.10\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\mch04019\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\capycli\__main__.py", line 13, in <module>
    cli.main()
  File "C:\Users\mch04019\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\capycli\main\cli.py", line 27, in main
    app.run(argv)
  File "C:\Users\mch04019\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\capycli\main\application.py", line 157, in run
    self._run(argv)
  File "C:\Users\mch04019\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\capycli\main\application.py", line 138, in _run
    handle_bom.run_bom_command(self.options)
  File "C:\Users\mch04019\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\capycli\bom\handle_bom.py", line 82, in run_bom_command
    app.run(args)
  File "C:\Users\mch04019\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\capycli\bom\map_bom.py", line 980, in run
    result = self.map_bom_to_releases(
  File "C:\Users\mch04019\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\capycli\bom\map_bom.py", line 524, in map_bom_to_releases
    self.external_id_svc.build_purl_cache(purl_types, self.verbosity <= 1)
  File "C:\Users\mch04019\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\capycli\common\purl_service.py", line 49, in build_purl_cache
    all_ids = all_ids + self.client.get_releases_by_external_id("package-url")
TypeError: can only concatenate list (not "dict") to list

I sent my converted and filtered BOM to Gernot so he may be able to check against our SW360 staging server.
Is there anything I can add to help?

**Comment by gernot-h** [comment]
Thanks, @Garbald! I will analyze it asap and come back to you if I still have questions about it. Sorry for the delay, I was on a business trip and later on ill last week.

**Comment by Garbald** [comment]
Ich sehe gerade, daß das letztens von poetry frisch installierte SW360 1.3.1 sich selber als Version 1.3.0 bezeichnet. Kann das relevant sein?

**Comment by gernot-h** [comment]
> Ich sehe gerade, daß das letztens von poetry frisch installierte SW360 1.3.1 sich selber als Version 1.3.0 bezeichnet. Kann das relevant sein?

Oh, that sounds interesting. Still had no time to look into it, but according to https://github.com/sw360/sw360python/pull/23, a problem which looks quite similar to the traceback above should be fixed in 1.3.1.

**Comment by Garbald** [comment]
Update: It seems that the self reported version 1.3.0 of sw360 was my mistake using the wrong python environment. If I use the real version 1.3.1 and the right python version, things work again. Sorry and thank you!

**Comment by gernot-h** [comment]
No problem, thanks for the update, @Garbald!
